# Generated by Django 6.0.3 on 2026-07-27 15:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schools', '0007_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fee_items', to='schools.school')),
            ],
            options={
                'db_table': 'billing_fee_items',
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(fields=('school', 'name'), name='unique_fee_item_name_per_school')],
            },
        ),
    ]
