# Generated by Django 6.0.3 on 2026-07-29 20:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
        ('schools', '0007_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fee_schedules', to='schools.academicsession')),
                ('academic_term', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fee_schedules', to='schools.academicterm')),
                ('class_level', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fee_schedules', to='schools.classlevel')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fee_schedules', to='schools.school')),
            ],
            options={
                'db_table': 'billing_fee_schedules',
                'ordering': ['class_level', 'academic_session', 'academic_term'],
                'constraints': [models.UniqueConstraint(fields=('school', 'academic_session', 'academic_term', 'class_level'), name='unique_fee_schedule_per_class_session_term')],
            },
        ),
    ]
