# Generated by Django 6.0.3 on 2026-07-30 09:02

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_feeschedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeScheduleItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fee_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fee_schedule_items', to='billing.feeitem')),
                ('fee_schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_schedule_items', to='billing.feeschedule')),
            ],
            options={
                'db_table': 'billing_fee_schedule_items',
                'ordering': ['fee_item'],
                'constraints': [models.UniqueConstraint(fields=('fee_schedule', 'fee_item'), name='unique_fee_item_per_fee_schedule')],
            },
        ),
    ]
