# Generated by Django 6.0.3 on 2026-07-30 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_feescheduleitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='feeitem',
            name='is_recurring',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='feeschedule',
            name='due_date',
            field=models.BooleanField(default=True),
        ),
    ]
