# Generated by Django 6.0.3 on 2026-07-30 20:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_feeitem_is_recurring_feeschedule_due_date'),
        ('people', '0005_enrollment'),
        ('schools', '0007_subject'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('discount_type', models.CharField(choices=[('DISCOUNT', 'Discount'), ('SCHOLARSHIP', 'Scholarship'), ('WAIVER', 'Waiver')], max_length=20)),
                ('value_type', models.CharField(choices=[('PERCENTAGE', 'Percentage'), ('FIXED_AMOUNT', 'Fixed Amount')], max_length=20)),
                ('value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reason', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='discounts', to='schools.academicsession')),
                ('academic_term', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='discounts', to='schools.academicterm')),
                ('approved_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='approved_discounts', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='discounts', to='schools.school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='discounts', to='people.student')),
            ],
            options={
                'db_table': 'billing_discounts',
                'ordering': ['student', 'academic_session', 'academic_term'],
                'constraints': [models.UniqueConstraint(fields=('student', 'academic_session', 'academic_term', 'discount_type'), name='unique_discount_per_student_term_type')],
            },
        ),
    ]
