# Generated by Django 6.0.3 on 2026-07-31 09:52

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0007_invoiceline_payment'),
        ('people', '0005_enrollment'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentCredit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('credit_note_number', models.CharField(editable=False, max_length=50, unique=True)),
                ('reason', models.CharField(choices=[('overpayment', 'Overpayment'), ('refund', 'Refund')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('remaining_amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='student_credits', to='billing.invoice')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='student_credits', to='billing.payment')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_credits', to='people.student')),
            ],
            options={
                'db_table': 'billing_student_credits',
                'ordering': ['-created_at'],
            },
        ),
    ]
