# Generated by Django 6.0.3 on 2026-08-03 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0011_webhookevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webhookevent',
            name='event_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AddConstraint(
            model_name='webhookevent',
            constraint=models.UniqueConstraint(fields=('provider', 'event_id'), name='unique_provider_event_id'),
        ),
    ]
