# Generated by Django 6.0.3 on 2026-07-20 18:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schools', '0007_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('admission_number', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10)),
                ('date_of_birth', models.DateField()),
                ('admission_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('class_arm', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='students', to='schools.classarm')),
                ('class_level', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='students', to='schools.classlevel')),
                ('current_session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='students', to='schools.academicsession')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='schools.school')),
            ],
            options={
                'db_table': 'students',
                'ordering': ['last_name', 'first_name'],
                'constraints': [models.UniqueConstraint(fields=('school', 'admission_number'), name='unique_student_admission_number_per_school')],
            },
        ),
    ]
