# Generated by Django 6.0.3 on 2026-07-20 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='admission_number',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterModelTable(
            name='student',
            table='people_students',
        ),
    ]
