# Generated by Django 6.0.3 on 2026-07-22 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_alter_student_admission_number_alter_student_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='class_arm',
        ),
        migrations.RemoveField(
            model_name='student',
            name='class_level',
        ),
        migrations.RemoveField(
            model_name='student',
            name='current_session',
        ),
    ]
