# Generated by Django 6.0.3 on 2026-07-23 09:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0004_guardian_studentguardian_and_more'),
        ('schools', '0007_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('active', 'Active'), ('promoted', 'Promoted'), ('transferred', 'Transferred'), ('withdrawn', 'Withdrawn'), ('graduated', 'Graduated')], default='active', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='schools.academicsession')),
                ('academic_term', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='schools.academicterm')),
                ('class_arm', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='schools.classarm')),
                ('class_level', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='schools.classlevel')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='schools.school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='people.student')),
            ],
            options={
                'db_table': 'people_enrollments',
                'ordering': ['-academic_session__start_date', 'student__last_name', 'student__first_name'],
                'constraints': [models.UniqueConstraint(fields=('student', 'academic_session'), name='unique_student_enrollment_per_session')],
            },
        ),
    ]
