# Generated by Django 6.0.3 on 2026-07-15 09:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0003_alter_school_code_alter_school_email_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='academicsession',
            table='schools_academic_sessions',
        ),
        migrations.CreateModel(
            name='AcademicTerm',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(choices=[('FIRST', 'First Term'), ('SECOND', 'Second Term'), ('THIRD', 'Third Term')], max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_current', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_terms', to='schools.academicsession')),
            ],
            options={
                'db_table': 'schools_academic_terms',
                'ordering': ['start_date'],
                'constraints': [models.UniqueConstraint(fields=('session', 'name'), name='unique_term_per_session')],
            },
        ),
    ]
