# Generated by Django 6.0.3 on 2026-07-16 13:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0005_classlevel'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='classlevel',
            table='schools_class_levels',
        ),
        migrations.CreateModel(
            name='ClassArm',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_arms', to='schools.classlevel')),
            ],
            options={
                'db_table': 'schools_class_arms',
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(fields=('level', 'name'), name='unique_class_arm_per_level')],
            },
        ),
    ]
